post/urls.py
from django.urls import path

from post import views

app_name = 'post'

urlpatterns = [
    path('', views.TopView.as_view(), name="top"),
    path('front/',views.FrontView.as_view(),name="front"),
    path('List/',views.PaymentListView.as_view(),name="list")
]

registration/urls.py
from django.urls import path

from registration import views

app_name = 'registration'

urlpatterns = [
    path('login/', views.Login.as_view(), name="login"),
    path('logout/', views.Login.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup")
]

timecard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('post.urls')),
    path('',include('registration.urls'))
]

post/models.py
from django.db import models

# Create your models here.

post/forms.py
from django import forms

from registration.models import CommutingTime


class TimeForm(forms.Form):
    class Meta:
        model = CommutingTime
        field = ['arrive_at_work', 'leave']

post/views.py
# Create your views here.
import datetime
from datetime import date

from django.db.models import Sum
from django.shortcuts import redirect
from django.utils import timezone
from django.views.generic import TemplateView, CreateView, ListView

from registration.models import CommutingTime


class TopView(TemplateView):
    template_name = 'post/top.html'


# やりたいこと、ボタンでユーザーに出社時間を記録させること
# まずはユーザーにリレーショナルで出社時間モデルを紐づける
class FrontView(CreateView):
    template_name = 'post/front.html'
    model = CommutingTime
    fields = []

    def form_valid(self, form):
        post = form.save(commit=False)
        post.user = self.request.user

        if "arrive_at_work" in self.request.POST:
            aaw = self.request.POST['arrive_at_work']
            post.arrive_at_work = timezone.datetime.today()
            if CommutingTime.objects.filter(user=self.request.user, arrive_at_work__istartswith=date.today()):
                return redirect('post:front')
            else:
                post.CommutingTime = CommutingTime(arrive_at_work=aaw)
                post.save()
            return redirect('post:front')
        else:
            leave_time = timezone.datetime.now()
            obj = CommutingTime.objects.filter(user=self.request.user, leave=None, arrive_at_work__isnull=False).first()
            if obj:
                obj.leave = leave_time
                obj.count = round((leave_time - obj.arrive_at_work).seconds / 60 / 60)
                obj.save()
                return redirect('post:front')

    def get_context_data(self, **kwargs):
        context = super(FrontView, self).get_context_data(**kwargs)
        context['commuting_times'] = CommutingTime.objects.filter(user=self.request.user, ).order_by('-arrive_at_work')[
                                     :5]
        mouth = datetime.date.today()
        count_sum = CommutingTime.objects.filter(arrive_at_work__istartswith='{0}-{1:02d}'.format(mouth.year,mouth.month)).aggregate(Sum('count'))['count__sum']
        context['count_sums'] = count_sum
        context['count_wage'] = count_sum * self.request.user.wage

        return context


class PaymentListView(ListView):
    template_name = 'post/PaymentList.html'
    model = CommutingTime

    def get_queryset(self):
        super(PaymentListView, self).get_queryset()
        queryset = CommutingTime.objects.filter(user=self.request.user, ).order_by('-arrive_at_work')
        return queryset

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/post/PaymentList.html
<a href="{% url 'post:front' %}">戻る</a>
<div>
    以下一覧↓
</div>
<hr>
<div>
    {% if user.is_authenticated %}

        {% for commuting_time in object_list %}
            出社時間：　{{ commuting_time.arrive_at_work }}
            {% if commuting_time.leave %}
                　　 退社時間：　{{ commuting_time.leave }}
                <p>あなたは、今日{{ commuting_time.get_tdhours }}時間働きました。。。お疲れ様です。。</p>
                <p>今月は合計{{ commuting_time.get_count }}時間働きました</p>
                <p>時給は{{ commuting_time.payment }}円なので</p>
                <p>今月もらえる額は{{ commuting_time.get_payment }}円です</p>
                <br>
                <hr>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>

templates/post/front.html
{% if user.is_authenticated %}
    <h1>こんにちは！{{ user.username }}さん</h1>
    <a href="{% url 'registration:logout' %}">ログアウト</a>

    <section>
        現在時刻:

        <p id="Clock1" style="display: inline"></p>
        <script type="text/javascript">
            setInterval('showClock1()', 1000);

            function showClock1() {
                var DWs = new Array('日曜日', '月曜日', '火曜日', '水曜日', '木曜日', '金曜日', '土曜日');
                var Now = new Date();
                var YY = Now.getYear();
                if (YY < 2000) {
                    YY += 1900;
                }
                var MM = set0(Now.getMonth() + 1);
                var DD = set0(Now.getDate());
                var DW = DWs[Now.getDay()];
                var hh = set0(Now.getHours());
                var mm = set0(Now.getMinutes());
                var ss = set0(Now.getSeconds());
                var RTime1 = ' ' + YY + '.' + MM + '.' + DD + ' ' + DW + ' ' + hh + ':' + mm + ':' + ss + ' ';
                document.getElementById("Clock1").innerHTML = RTime1;
            }

            function set0(num) {
                var ret;
                if (num < 10) {
                    ret = "0" + num;
                } else {
                    ret = num;
                }
                return ret;
            }
        </script>
    </section>
    <div>

        <p>今月は合計:{{ count_sums }}時間働きました。。。</p>

    </div>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            <button type="submit" name="arrive_at_work" value="arrive_at_work">
                出社する
            </button>

        </form>
    </div>

    <div>
        <form action="" method="post">
            {% csrf_token %}
            <button type="submit" value="leave" name="leave">
                退社する
            </button>
        </form>
        <p>上位5件を表示しています。</p>
        <div>


            {% for commuting_time in commuting_times %}
                出社時間：　{{ commuting_time.arrive_at_work }}
                {% if commuting_time.leave %}
                    　　 退社時間：　{{ commuting_time.leave }}
                    <p>あなたは、今日{{ commuting_time.get_tdhours }}時間働きました。。。お疲れ様です。。</p>
                    <p>今月は合計{{ commuting_time.count}}時間働きました</p>
                    <p>時給は{{ user.wage }}円なので</p>
                    <p>今月もらえる額は{{ count_wage }}円です</p>
                    <br>
                    <hr>
                {% endif %}
            {% endfor %}

            {{ message }}


        </div>
        <a href="{% url 'post:list' %}">もっと見る</a>

        <p>これまでの履歴を月ごとに確認できる</p>

{% endif %}

templates/post/top.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TopPage</title>
</head>
<body>
<p>タイムカードです</p>
<a href="{% url 'registration:login'%}">ログイン</a>
<a href="{% url 'registration:signup' %}">新規登録</a>
</body>
</html>

templates/post/userdetail.html
{{ user.username }}さんの詳細ページです
{{ user.arrive_at_work }}